id: PB55F699D
initial_creation_type: input
source_metadata:
  title: Lala Sonam Chödrup Series
  language: bo
  description: Lala Sönam Chödrup (glag bla bsod nams chos 'grub, 1862–1944) of Nyarong
    was regarded as a speech emanation of Dzogchen Pema Rigdzin. He is best-known
    for his biography of Longchenpa and his commentary on the Aspiration of Sukhāvatī.
  volume:
    2838759465664887a576f3c669e6a6e9:
      title: Prayer of Aspiration Incorporating the Eight Thoughts of Great Beings
        Who Follow the Way of the Mahāyāna
      parent: Aspiration Prayers
    9b45c564381a4742b8cde6bfe10143a6:
      title: A Brief Guide to Samaya Commitment
      parent: Samaya
created_at: '2022-03-01T00:33:14.574975'
last_modified_at: '2022-03-01T00:33:14.574982'
